"""
Stage 5 -- Export a .tflite model as a C header array for TFLite Micro on Arduino.

Usage:
    python scripts/06_export_c_array.py --tflite_path results/stage2_ds_cnn_int8/model_int8.tflite \
        --out arduino/wake_word_detection/model_data.h --var_name g_model

After running this, copy/overwrite arduino/wake_word_detection/model_data.h
with the freshly generated file before compiling the sketch.
"""
import argparse
import os


def to_c_array(data: bytes, var_name: str) -> str:
    lines = []
    lines.append("// Auto-generated by scripts/06_export_c_array.py -- do not hand-edit.")
    lines.append("// This is the trained, quantized wake-word model as a byte array")
    lines.append("// for TFLite Micro's interpreter to load directly from flash.")
    lines.append("#ifndef MODEL_DATA_H_")
    lines.append("#define MODEL_DATA_H_")
    lines.append("")
    lines.append(f"alignas(8) const unsigned char {var_name}[] = {{")
    for i in range(0, len(data), 12):
        chunk = data[i:i + 12]
        row = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"  {row},")
    lines.append("};")
    lines.append(f"const int {var_name}_len = {len(data)};")
    lines.append("")
    lines.append("#endif  // MODEL_DATA_H_")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tflite_path", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--var_name", default="g_model")
    args = ap.parse_args()

    with open(args.tflite_path, "rb") as f:
        data = f.read()

    header = to_c_array(data, args.var_name)
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w") as f:
        f.write(header)

    print(f"Wrote {len(data)} bytes ({len(data)/1024:.1f} KB) as C array to {args.out}")
    print(f"Array name: {args.var_name}, length symbol: {args.var_name}_len")
    print("This model must fit comfortably under the Nano 33 BLE Sense's ~1MB flash")
    print("budget alongside the sketch itself and the TFLite Micro runtime.")


if __name__ == "__main__":
    main()
